name: Deploy to GitHub Pages

on:
  push:
    branches:
      - docs/swagger

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Uploading Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploying to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
