name: Test Code

on:
  push:
    branches:
      - dev

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.12.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Installing Project Dependencies
        run: pnpm install

      - name: Building Project
        run: pnpm build

      - name: Set Up Environment File
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BASE_PATH: /api
          envkey_CLUSTERING: false
          envkey_PORT: 3000
          envkey_NODE_ENV: production

      - name: Running Test
        run: pnpm test
